# Site settings
title: "Begin's Recipe Book"
description: "A blog about begins' recipe book"
baseurl: "/recipe"
url: "https://kyungmi-park.github.io"
#baseurl:
#url: "http://localhost:3000"

# User settings
username: Kyungmi Park
user_description: Researcher and Cook
email: park.kyungmi@gmail.com
github_username: kyungmi-park

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
